version: '3'

output: prefixed

vars:
  BUILD_DIR: /build

dotenv:
  - '{{.BUILD_DIR}}/.env'
  - '.env'

tasks:
  create-build-directory:
    desc: Create build directory
    status:
    - test -d {{.BUILD_DIR}}/cache
    - test -d {{.BUILD_DIR}}/install
    cmds:
    - mkdir -p {{.BUILD_DIR}}/cache
    - mkdir -p {{.BUILD_DIR}}/install

  chown-build-directory:
    desc: Change owner of build directory
    cmds:
      - cmd: chown -R {{.CLI_ARGS}} {{.BUILD_DIR}}
        ignore_error: true


