version: '3'

includes:
  builder:
    taskfile: ../../../builder
    dir: ../../../ubuntu/22.04
    internal: true
    vars:
      OSNAME: 'ubuntu-22.04'
      ASTERISK_VERSION_NUM: 181000

tasks:
  armhf:
    desc: Build chan_quectel for ARM on Ubuntu 22.04 using GNU Toolchain
    deps:
      - builder:armhf-ext

  arm64:
    desc: Build chan_quectel for ARM64 on Ubuntu 22.04 using GNU Toolchain
    deps:
      - builder:arm64-ext