version: '3'

includes:
  10:
    taskfile: 10
    dir: 10
    aliases: [buster]
  11:
    taskfile: 11
    dir: 11
    aliases: [bullseye]
  12:
    taskfile: 12
    dir: 12
    aliases: [bookworm]

tasks:
  clean:
    desc: Remove package directories
    deps:
    - 10:clean
    - 11:clean
    - 12:clean

  native:
    aliases: [default]
    desc: Build chan_quectel on Raspberry Pi OS
    deps:
    - 10:native
    - 11:native
    - 12:native
