version: '3'

output: prefixed

vars:
  BUILD_DIR: /build

dotenv:
  - '{{.BUILD_DIR}}/.env'
  - '.env'

tasks:
  clone:
    desc: Fetch chan-quectel sources
    preconditions:
      - test -n "{{.PRESET}}"
    dir: '{{.BUILD_DIR}}'
    cmds:
      - git clone -q --branch={{.BRANCH}} http://github.com/RoEdAl/asterisk-chan-quectel.git chan-quectel

  configure:
    desc: Create CMake presets
    dotenv: ['{{.BUILD_DIR}}/buildflags.env']
    preconditions:
      - test -n "{{.PRESET}}"
    dir: '{{.BUILD_DIR}}/chan-quectel'
    cmds:
      - cmd: |
          {
            ./get-source-date-epoch.sh
            {{if .RPI_VERSION}}echo 'TOOLSET_TARGET_RPI={{.RPI_VERSION}}'{{end}}
          } >> {{.BUILD_DIR}}/.env
        silent: true
      - ./get-build-flags.sh {{.PRESET}}-env > CMakeUserPresets.json

  build:
    desc: Build chan_quectel packages
    preconditions:
      - test -n "{{.PRESET}}"
    dir: '/build/chan-quectel' # bug - unable to set to '{{.BUILD_DIR}}/chan-quectel', templating is broken
    vars:
      NINJA_BUILDER:
        sh: 'command -v ninja || true'
      CACHE_DIR_EMPTY:
        sh: find {{.BUILD_DIR}}/cache -maxdepth 0 -empty
      AST_HEADER_DIR:
        sh: |
          if test -z "{{.CACHE_DIR_EMPTY}}"; then
            echo '{{.BUILD_DIR}}/cache'
          elif test -s '{{.BUILD_DIR}}/asterisk-headers/asterisk.h'; then
            echo '{{.BUILD_DIR}}/asterisk-headers'
          fi
    cmds:
      - >-
        cmake --preset={{.PRESET}} --log-level={{if .CMAKE_VERBOSE}}VERBOSE{{else}}STATUS{{end}}
        {{if .NINJA_BUILDER}}-G Ninja{{end}}
        {{if .CC_TOOLCHAIN}}--toolchain=cmake/toolchain/{{.CC_TOOLCHAIN}}.toolchain.cmake{{end}}
        {{if .ASTERISK_VERSION_NUM}}-DASTERISK_VERSION_NUM={{.ASTERISK_VERSION_NUM}}{{end}}
        {{if .AST_HEADER_DIR}}-DAST_HEADER_DIR={{.AST_HEADER_DIR}}{{end}}
      - cmake --build --preset=package-{{.PRESET}} {{if .CMAKE_VERBOSE}}-v{{end}}

  test:
    desc: Test chan_quectel library
    preconditions:
      - test -n "{{.PRESET}}"
    dir: '{{.BUILD_DIR}}/chan-quectel'
    cmds:
      - ctest --preset={{.PRESET}} {{if .CMAKE_VERBOSE}}-V{{end}}
