version: '3'

output: prefixed

vars:
  BUILD_DIR: /build

dotenv:
  - '{{.BUILD_DIR}}/.env'
  - '.env'

tasks:
  configure:
    desc: Set Asterisk build options
    internal: true
    required:
      vars: [DISABLED_CONFS, MENU_ENABLE, MENU_DISABLE]
    dir: '{{.BUILD_DIR}}/asterisk'
    cmds:
    - cmd: >-
        ./configure
        --with-download-cache={{.BUILD_DIR}}/cache
        --prefix=/usr
        --sysconfdir=/etc
        --localstatedir=/var
        --bindir=/usr/bin
        --sbindir=/usr/bin
        --disable-xmldoc
        --disable-dev-mode
        --disable-internal-poll
        --with-jansson-bundled
        {{range $i, $opt := .DISABLED_CONFS | splitList " "}}
        --without-{{$opt}}
        {{end}}
    - cmd: make menuselect.makeopts
    - cmd: >-
        menuselect/menuselect
        {{range $i, $opt := .MENU_ENABLE | splitList " "}}
        --enable {{$opt}}
        {{end}}
        {{range $i, $opt := .MENU_DISABLE | splitList " "}}
        --disable {{$opt}}
        {{end}}

  old-configure-16:
    desc: Prepare Asterisk 16 sources (OLD)
    cmds:
    - task: configure
      vars:
        DISABLED_CONFS: >-
          oss
          portaudio
          jack
          x11
          vpb
          gtk2
          gmime
          sdl
          avcodec
          bluetooth
          iodbc
          imap
          inotify
          sqlite
          sndfile
          mysqlclient
          postgres
          iksemel
          openr2
          radius
          resample
          spandsp
          tds
          neon29
          neon
          pri
          ss7
          dahdi
          misdn
          suppserv
          tonezone
          fftw3
          unbound
          vorbis
          speex
          speexdsp
          ogg
          ilbc
          opus
          opusfile
          vpb
        MENU_ENABLE: >-
          LOW_MEMORY
          func_speex
          res_snmp
          app_url
          app_flash
        MENU_DISABLE: >-
          BUILD_NATIVE
          codec_speex
          codec_ilbc
          codec_lpc10
          codec_g726
          codec_adpcm
          cdr_syslog
          cdr_sqlite3_custom
          cel_sqlite3_custom
          format_gsm
          format_wav_gsm
          format_siren7
          format_siren14
          format_ilbc
          format_g719
          format_g723
          format_g726
          format_h263
          format_h264
          format_vox
          res_fax
          res_fax_spandsp
          res_format_attr_h263
          res_format_attr_h264
          res_config_pgsql
          res_format_attr_siren14
          res_format_attr_siren7
          res_format_attr_vp8
          res_format_attr_ilbc
          res_speech
          res_config_ldap
          res_format_attr_silk
          res_adsi
          res_monitor
          app_festival
          app_mp3
          app_ices
          app_image
          app_sms
          app_nbscat
          app_test
          chan_sip
          chan_skinny
          chan_unistim
          chan_iax2
          chan_mgcp
          chan_motif
          astdb2sqlite3
          astdb2bdb
          astcanary
          CORE-SOUNDS-EN-WAV
          CORE-SOUNDS-EN-GSM
          CORE-SOUNDS-EN-G722
          MOH-OPSOUND-WAV
          MOH-OPSOUND-GSM
          MOH-OPSOUND-G722
          EXTRA-SOUNDS-EN-WAV
          EXTRA-SOUNDS-EN-GSM
          EXTRA-SOUNDS-EN-G722

  configure-18:
    desc: Prepare Asterisk 18 sources
    cmds:
    - task: configure
      vars:
        DISABLED_CONFS: >-
          oss
          portaudio
          jack
          x11
          vpb
          gtk2
          gmime
          sdl
          avcodec
          bluetooth
          iodbc
          imap
          inotify
          sqlite
          sndfile
          mysqlclient
          postgres
          iksemel
          openr2
          radius
          resample
          spandsp
          tds
          neon29
          neon
          pri
          ss7
          dahdi
          misdn
          suppserv
          tonezone
          fftw3
          unbound
          vorbis
          speex
          speexdsp
          ogg
          ilbc
          opus
          opusfile
          vpb
        MENU_ENABLE: >-
          LOW_MEMORY
          func_speex
          res_snmp
          app_url
          app_flash
        MENU_DISABLE: >-
          BUILD_NATIVE
          codec_speex
          codec_ilbc
          codec_lpc10
          codec_g726
          codec_adpcm
          cdr_syslog
          cdr_sqlite3_custom
          cel_sqlite3_custom
          format_gsm
          format_wav_gsm
          format_siren7
          format_siren14
          format_ilbc
          format_g719
          format_g723
          format_g726
          format_h263
          format_h264
          format_vox
          res_fax
          res_fax_spandsp
          res_format_attr_h263
          res_format_attr_h264
          res_config_pgsql
          res_format_attr_siren14
          res_format_attr_siren7
          res_format_attr_vp8
          res_format_attr_ilbc
          res_speech
          res_config_ldap
          res_format_attr_silk
          res_adsi
          res_monitor
          app_festival
          app_mp3
          app_ices
          app_image
          app_sms
          app_nbscat
          app_test
          chan_sip
          chan_skinny
          chan_unistim
          chan_iax2
          chan_mgcp
          chan_motif
          astdb2sqlite3
          astdb2bdb
          astcanary
          CORE-SOUNDS-EN-WAV
          CORE-SOUNDS-EN-GSM
          CORE-SOUNDS-EN-G722
          MOH-OPSOUND-WAV
          MOH-OPSOUND-GSM
          MOH-OPSOUND-G722
          EXTRA-SOUNDS-EN-WAV
          EXTRA-SOUNDS-EN-GSM
          EXTRA-SOUNDS-EN-G722

  configure-20:
    desc: Prepare Asterisk 20 sources
    cmds:
    - task: configure
      vars:
        DISABLED_CONFS: >-
          portaudio
          jack
          x11
          gtk2
          gmime
          sdl
          avcodec
          bluetooth
          iodbc
          imap
          inotify
          sndfile
          mysqlclient
          postgres
          iksemel
          openr2
          radius
          resample
          spandsp
          tds
          neon29
          neon
          pri
          ss7
          dahdi
          tonezone
          fftw3
          unbound
          vorbis
          speex
          speexdsp
          ogg
          ilbc
          opus
          opusfile
        MENU_ENABLE: >-
          LOW_MEMORY
          func_speex
          res_snmp
          app_flash
        MENU_DISABLE: >-
          BUILD_NATIVE
          codec_speex
          codec_ilbc
          codec_lpc10
          codec_g726
          codec_adpcm
          cdr_sqlite3_custom
          cel_sqlite3_custom
          format_gsm
          format_wav_gsm
          format_siren7
          format_siren14
          format_ilbc
          format_g719
          format_g723
          format_g726
          format_h263
          format_h264
          format_vox
          res_fax
          res_fax_spandsp
          res_format_attr_h263
          res_format_attr_h264
          res_config_pgsql
          res_format_attr_siren14
          res_format_attr_siren7
          res_format_attr_vp8
          res_format_attr_ilbc
          res_speech
          res_config_ldap
          res_format_attr_silk
          res_adsi
          res_monitor
          app_festival
          app_mp3
          app_sms
          app_test
          chan_sip
          chan_skinny
          chan_unistim
          chan_iax2
          chan_mgcp
          chan_motif
          astdb2sqlite3
          astdb2bdb
          astcanary
          CORE-SOUNDS-EN-WAV
          CORE-SOUNDS-EN-GSM
          CORE-SOUNDS-EN-G722
          MOH-OPSOUND-WAV
          MOH-OPSOUND-GSM
          MOH-OPSOUND-G722
          EXTRA-SOUNDS-EN-WAV
          EXTRA-SOUNDS-EN-GSM
          EXTRA-SOUNDS-EN-G722
      
  extract-sources:
    desc: Extract Asterisk sources
    preconditions:
      - test -n "{{.ASTVER}}"
      - test -d "{{.BUILD_DIR}}/download"
    dir: '{{.BUILD_DIR}}/asterisk'
    cmds:
      - tar -xf {{.BUILD_DIR}}/download/asterisk-{{.ASTVER}}-current.tar.gz --strip-components=1

  old-extract-sources:
    desc: Extract Asterisk sources (OLD)
    preconditions:
      - test -n "{{.ASTVER}}"
      - test -d "{{.BUILD_DIR}}/download"
    dir: '{{.BUILD_DIR}}/asterisk'
    cmds:
      - tar -xf {{.BUILD_DIR}}/download/asterisk-{{.ASTVER}}.tar.gz --strip-components=1
   
  build:
    desc: Build Asterisk
    dir: '{{.BUILD_DIR}}/asterisk'
    env:
      OPTIMIZE: '-fmerge-constants'
    cmds:
      - make -j$(nproc)

  install-headers:
    desc: Install Asterisk headers
    dir: '{{.BUILD_DIR}}/asterisk'
    env:
      DESTDIR: '{{.BUILD_DIR}}/install'
    cmds:
      - make install-headers
