name: Download OpenWRT SDK
description: Download, extract and prepare OpenWRT SDK for specific target
inputs:
  openwrt-version:
    required: true
    description: OpenWRT version
  target:
    required: true
    description: Target-subtarget pair
  arch:
    required: false
    description: Archtecture name
  eabi:
    required: false
    description: EABI
    default: false
  kirkwood:
    required: false
    description: Kirkwood
    default: false
runs:
  using: composite
  steps:
    - name: Restore OpenWRT SDK from cache (${{ inputs.arch }})
      id: cache-owrt-sdk-restore
      uses: actions/cache/restore@v3
      with:
        path: owrtsdk
        key: openwrt-sdk-${{ inputs.openwrt-version }}-${{ inputs.target }}

    - name: Prepare OpenWRT SDK directory
      id: prepare-owrt-sdk-dir
      if: steps.cache-owrt-sdk-restore.outputs.cache-hit != 'true'
      shell: bash
      run: mkdir owrtsdk

    - name: Download OpenWRT SDK (eabi)
      id: download-owrt-sdk-eabi
      if: steps.cache-owrt-sdk-restore.outputs.cache-hit != 'true' && inputs.kirkwood != 'true' && inputs.eabi == 'true'
      shell: bash
      working-directory: owrtsdk
      run: ${{ github.action_path }}/download-owrt-sdk.sh ${{ inputs.target }} ${{ inputs.openwrt-version }} openwrt-sdk-${{ inputs.openwrt-version }}-${{ inputs.target }}_gcc-11.2.0_musl_eabi.Linux-x86_64

    - name: Download OpenWRT SDK (kirkwood)
      id: download-owrt-sdk-kirkwood
      if: steps.cache-owrt-sdk-restore.outputs.cache-hit != 'true' && inputs.kirkwood == 'true' && inputs.eabi == 'true'
      shell: bash
      working-directory: owrtsdk
      run: ${{ github.action_path }}/download-owrt-sdk.sh ${{ inputs.target }} ${{ inputs.openwrt-version }} openwrt-sdk-${{ inputs.openwrt-version }}-kirkwood_gcc-11.2.0_musl_eabi.Linux-x86_64      

    - name: Download OpenWRT SDK
      id: download-owrt-sdk
      if: steps.cache-owrt-sdk-restore.outputs.cache-hit != 'true' && inputs.kirkwood != 'true' && inputs.eabi != 'true'
      shell: bash
      working-directory: owrtsdk
      run: ${{ github.action_path }}/download-owrt-sdk.sh ${{ inputs.target }} ${{ inputs.openwrt-version }} openwrt-sdk-${{ inputs.openwrt-version }}-${{ inputs.target }}_gcc-11.2.0_musl.Linux-x86_64

    - name: Prepare OpenWRT SDK
      id: prepare-owrt-sdk
      if: steps.cache-owrt-sdk-restore.outputs.cache-hit != 'true'
      shell: bash
      working-directory: owrtsdk/${{ inputs.target }}
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Cache OpenWRT SDK (${{ inputs.arch }})
      id: cache-owrt-sdk-save
      if: steps.cache-owrt-sdk-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: owrtsdk
        key: ${{ steps.cache-owrt-sdk-restore.outputs.cache-primary-key }}
