name: Download OpenWRT SDK
description: Download, extract and prepare OpenWRT SDK for specific target (architecture)
inputs:
  openwrt-version:
    required: true
    description: OpenWRT version
  arch:
    required: true
    description: Target name
  eabi:
    required: false
    description: EABI
    default: false
runs:
  using: composite
  steps:
    - name: Restore OpenWRT SDK from cache
      id: cache-owrt-sdk-restore
      uses: actions/cache/restore@v3
      with:
        path: owrtsdk
        key: openwrt-sdk-${{ inputs.openwrt-version }}-${{ inputs.arch }}

    - name: Prepare OpenWRT SDK directory
      id: prepare-owrt-sdk-dir
      if: steps.cache-owrt-sdk-restore.outputs.cache-hit != 'true'
      shell: bash
      run: mkdir owrtsdk

    - name: Download OpenWRT SDK (eabi)
      id: download-owrt-sdk-eabi
      if: steps.cache-owrt-sdk-restore.outputs.cache-hit != 'true' && inputs.eabi == 'true'
      shell: bash
      working-directory: owrtsdk
      run: ${{ github.action_path }}/download-owrt-sdk.sh ${{ inputs.arch }} ${{ inputs.openwrt-version }} openwrt-sdk-${{ inputs.openwrt-version }}-${{ inputs.arch }}_gcc-11.2.0_musl_eabi.Linux-x86_64

    - name: Download OpenWRT SDK
      id: download-owrt-sdk
      if: steps.cache-owrt-sdk-restore.outputs.cache-hit != 'true' && inputs.eabi != 'true'
      shell: bash
      working-directory: owrtsdk
      run: ${{ github.action_path }}/download-owrt-sdk.sh ${{ inputs.arch }} ${{ inputs.openwrt-version }} openwrt-sdk-${{ inputs.openwrt-version }}-${{ inputs.arch }}_gcc-11.2.0_musl.Linux-x86_64

    - name: Prepare OpenWRT SDK
      id: prepare-owrt-sdk
      if: steps.cache-owrt-sdk-restore.outputs.cache-hit != 'true'
      shell: bash
      working-directory: owrtsdk/${{ inputs.arch }}
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Cache OpenWRT SDK
      id: cache-owrt-sdk-save
      if: steps.cache-owrt-sdk-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: owrtsdk
        key: ${{ steps.cache-owrt-sdk-restore.outputs.cache-primary-key }}
