version: '3'

includes:
  20.04:
    taskfile: 20.04
    dir: 20.04
    aliases: [focal, focal-fossa]    
  22.04:
    taskfile: 22.04
    dir: 22.04
    aliases: [jammy, jammy-jellyfish]
  24.04:
    taskfile: 24.04
    dir: 24.04
    aliases: [noble, noble-numbat]

tasks:
  clean:
    desc: Remove package directories
    deps:
    - 20.04:clean
    - 22.04:clean
    - 24.04:clean

  native:
    aliases: [default]
    desc: Build chan_quectel on Ubuntu
    deps:
    - 20.04:native
    - 22.04:native
    - 24.04:native

  armhf:
    desc: Build chan_quectel for ARM on Ubuntu
    deps:
    - 20.04:armhf
    - 22.04:armhf

  arm64:
    desc: Build chan_quectel for ARM64 on Ubuntu
    deps:
    - 20.04:arm64
    - 22.04:arm64
    - 24.04:arm64
