version: '3'

tasks:
  import-dir:
    internal: true
    requires:
      vars: [IMG_DIR, IMG_NAME]
    dir: '{{.IMG_DIR}}'
    cmds:
      - tar -c . --mtime=@ | docker import --platform=linux/arm/v6 --change "ENTRYPOINT /bin/bash" - {{.IMG_NAME}}

  import-img:
    internal: true
    requires:
      vars: [DEV_BOOT, DEV_ROOT, IMG_NAME]
    preconditions:
      - test -b {{.DEV_BOOT}}
      - test -b {{.DEV_ROOT}}
    vars:
      MNT_POINT:
        sh: mktemp -d --suffix={{randInt 0 1000000}}
    cmds:
      - mount -o ro {{.DEV_ROOT}} {{.MNT_POINT}}
      - mount -o ro {{.DEV_BOOT}} {{.MNT_POINT}}/boot
      - task: import-dir
        vars:
          IMG_DIR: '{{.MNT_POINT}}'
          IMG_NAME: '{{.IMG_NAME}}'
      - defer: rm -rf {{.MNT_POINT}}
      - defer: umount -q -R {{.MNT_POINT}}

  import-dev:
    internal: true
    requires:
      vars: [BLOCK_DEV, IMG_NAME]
    preconditions:
      - test -b {{.BLOCK_DEV}}
    cmds:
      - task: import-img
        vars:
          DEV_BOOT: '{{.BLOCK_DEV}}p1'
          DEV_ROOT: '{{.BLOCK_DEV}}p2'
          IMG_NAME: '{{.IMG_NAME}}'
    
  import-sdcard-img:
    internal: true
    requires:
      vars: [IMG_FILE, IMG_NAME]
    preconditions:
      - test -s {{.IMG_FILE}}
      - test -r {{.IMG_FILE}}
    vars:
      LOOP_DEV:
        sh: losetup -rPf --show {{.IMG_FILE}}
    cmds:
      - task: import-dev
        vars:
          BLOCK_DEV: '{{.LOOP_DEV}}'
          IMG_NAME: '{{.IMG_NAME}}'
      - defer: losetup -d {{.LOOP_DEV}}

  download-raspbx:
    internal: true
    requires:
      vars: [DL_DIR, RASPBX_IMG]
    dir: '{{.DL_DIR}}'
    cmds:
      - wget http://download.raspbx.org/{{.RASPBX_IMG}}
      - cmake -E tar -xf {{.RASPBX_IMG}}
      - rm {{.RASPBX_IMG}}

  import-raspbx:
    internal: false
    vars:
      IMG_TS: 11-11-2019
      IMG_EPOCH: '{{mustToDate "02-01-2006" .IMG_TS | unixEpoch}}'
      DL_DIR:
        sh: mktemp -p /var/tmp -d --suffix={{randInt 0 1000000}}
    cmds:
      - cmd: 'echo Epoch: {{.IMG_EPOCH}}'
      - false
      - task: download-raspbx
        vars:
          DL_DIR: '{{.DL_DIR}}'
          RASPBX_IMG: 'raspbx-{{.IMG_TS}}.zip'
      - task: import-sdcard-img
        vars:
          IMG_FILE: '{{.DL_DIR}}/raspbx-{{.IMG_TS}}.img'
          IMG_NAME: 'raspbx:20191111'
      - defer: rm -rf {{.DL_DIR}}
