version: '3'

output: prefixed

vars:
  BUILD_DIR: /build

dotenv:
  - '{{.BUILD_DIR}}/.env'
  - '.env'

tasks:
  install-pkgs:
    desc: Install specified packages (DEB)
    aliases: [deb-install-pkgs]
    env:
      DEBIAN_FRONTEND: noninteractive
    cmds:
    - cmd: apt-get -qq update -y
      silent: true
    - apt-get -qq install -y --no-install-recommends {{.CLI_ARGS}}

  yum-install-pkgs:
    desc: Install specified packages (RPM)
    cmds:
    - cmd: yum update -y -q
      silent: true
    - yum install -y -q {{.CLI_ARGS}}    

  install-pkgs-arch:
    desc: Adds architecture and install specified packages
    preconditions:
      - test -n "{{.CC_TARGET}}"
    env:
      DEBIAN_FRONTEND: noninteractive
    cmds:
    - dpkg --add-architecture {{.CC_TARGET}}
    - cmd: apt-get -qq update -y
      silent: true
    - apt-get -qq install -y --no-install-recommends {{.CLI_ARGS}}    

  create-build-directory:
    desc: Create build directory
    status:
    - test -d {{.BUILD_DIR}}/cache
    - test -d {{.BUILD_DIR}}/install
    cmds:
    - mkdir -p {{.BUILD_DIR}}/cache
    - mkdir -p {{.BUILD_DIR}}/install

  chown-build-directory:
    desc: Change owner of build directory
    cmds:
      - cmd: chown -R {{.CLI_ARGS}} {{.BUILD_DIR}}
        ignore_error: true

  create-dotenv:
    desc: Create .env file
    aliases: [deb-create-dotenv]
    status:
      - test -f {{.BUILD_DIR}}/.env
    env:
        DEB_BUILD_OPTIONS: reproducible=-fixfilepath,-fixdebugpath
    cmds:
    - cmd: |
        eval "$(env dpkg-buildflags --export=sh)"
        {
          echo "CFLAGS='${CFLAGS} ${CPPFLAGS}'"
          echo "CXXFLAGS='${CXXFLAGS} ${CPPFLAGS}'"
          echo "LDFLAGS='${LDFLAGS}'"
        } > {{.BUILD_DIR}}/.env
      silent: true

  rpm-create-dotenv:
    desc: Create .env file (RPM)
    status:
      - test -f {{.BUILD_DIR}}/.env
    cmds:
    - cmd: |
        {
          echo "CFLAGS='$(rpm -E '%optflags')'"
          echo "CXXFLAGS='$(rpm -E '%optflags')'"
          echo "LDFLAGS='$(rpm -E '%__global_ldflags')'"
        } > {{.BUILD_DIR}}/.env
      silent: true      

  arm-gnu-toolchain-create-directory:
    desc: Create directory for ARM GNU Toolchains
    status:
      - test -d {{.BUILD_DIR}}/arm-gnu-toolchain
    cmds:
      - mkdir -p {{.BUILD_DIR}}/arm-gnu-toolchain
      - cmd: chown -R nobody:nogroup {{.BUILD_DIR}}
        ignore_error: true
  
  arm-gnu-toolchain-link-*:
    internal: true
    vars:
      TOOLCHAIN: '{{index .MATCH 0}}'
    dir: '{{.BUILD_DIR}}/arm-gnu-toolchain'
    cmds:
      - ln -s arm-gnu-toolchain-*-x86_64-{{.TOOLCHAIN}} {{.TOOLCHAIN}}

  arm-gnu-toolchain-extract-*:
    internal: true
    vars:
      TOOLCHAIN: '{{index .MATCH 0}}'
    dir: '{{.BUILD_DIR}}/download'
    cmds:
      - tar -xf arm-gnu-toolchain-{{.ARM_GNU_TOOLCHAIN_VER}}-x86_64-{{.TOOLCHAIN}}.tar.xz -C {{.BUILD_DIR}}/arm-gnu-toolchain

  arm-gnu-toolchain-prepare-pkg-*:
    internal: true
    vars:
      TOOLCHAIN: '{{index .MATCH 0}}'
    cmds:
      - task: arm-gnu-toolchain-extract-{{.TOOLCHAIN}}
      - task: arm-gnu-toolchain-link-{{.TOOLCHAIN}}

  arm-gnu-toolchain-prepare:
    desc: Prepare ARM GNU Toolchain package
    preconditions:
      - test -n "{{.ARM_GNU_TOOLCHAIN_VER}}"
      - test -d "{{.BUILD_DIR}}/arm-gnu-toolchain"
    dir: '{{.BUILD_DIR}}/download'
    deps:
      - arm-gnu-toolchain-prepare-pkg-arm-none-linux-gnueabihf
      - arm-gnu-toolchain-prepare-pkg-aarch64-none-linux-gnu

  asterisk-configure:
    desc: Set Asterisk build options
    internal: true
    required:
      vars: [ASTDIR, DISABLED_CONFS, MENU_ENABLE, MENU_DISABLE]
    dir: '{{.ASTDIR}}'
    cmds:
    - cmd: >-
        ./configure
        --with-download-cache={{.BUILD_DIR}}/cache
        --prefix=/usr
        --sysconfdir=/etc
        --localstatedir=/var
        --bindir=/usr/bin
        --sbindir=/usr/bin
        --disable-xmldoc
        --disable-dev-mode
        --disable-internal-poll
        --with-jansson-bundled
        {{range $i, $opt := .DISABLED_CONFS | splitList " "}}
        --without-{{$opt}}
        {{end}}
    - cmd: make menuselect.makeopts
    - cmd: >-
        menuselect/menuselect
        {{range $i, $opt := .MENU_ENABLE | splitList " "}}
        --enable {{$opt}}
        {{end}}
        {{range $i, $opt := .MENU_DISABLE | splitList " "}}
        --disable {{$opt}}
        {{end}}

  old-asterisk-configure-16:
    desc: Prepare Asterisk 16 sources (OLD)
    dir: '{{.BUILD_DIR}}/asterisk-{{.ASTVER}}'
    cmds:
    - task: asterisk-configure
      vars:
        ASTDIR: '{{.BUILD_DIR}}/asterisk-{{.ASTVER}}'
        DISABLED_CONFS: >-
          oss
          portaudio
          jack
          x11
          vpb
          gtk2
          gmime
          sdl
          avcodec
          bluetooth
          iodbc
          imap
          inotify
          sqlite
          sndfile
          mysqlclient
          postgres
          iksemel
          openr2
          radius
          resample
          spandsp
          tds
          neon29
          neon
          pri
          ss7
          dahdi
          misdn
          suppserv
          tonezone
          fftw3
          unbound
          vorbis
          speex
          speexdsp
          ogg
          ilbc
          opus
          opusfile
          vpb
        MENU_ENABLE: >-
          LOW_MEMORY
          func_speex
          res_snmp
          app_url
          app_flash
        MENU_DISABLE: >-
          BUILD_NATIVE
          codec_speex
          codec_ilbc
          codec_lpc10
          codec_g726
          codec_adpcm
          cdr_syslog
          cdr_sqlite3_custom
          cel_sqlite3_custom
          format_gsm
          format_wav_gsm
          format_siren7
          format_siren14
          format_ilbc
          format_g719
          format_g723
          format_g726
          format_h263
          format_h264
          format_vox
          res_fax
          res_fax_spandsp
          res_format_attr_h263
          res_format_attr_h264
          res_config_pgsql
          res_format_attr_siren14
          res_format_attr_siren7
          res_format_attr_vp8
          res_format_attr_ilbc
          res_speech
          res_config_ldap
          res_format_attr_silk
          res_adsi
          res_monitor
          app_festival
          app_mp3
          app_ices
          app_image
          app_sms
          app_nbscat
          app_test
          chan_sip
          chan_skinny
          chan_unistim
          chan_iax2
          chan_mgcp
          chan_motif
          astdb2sqlite3
          astdb2bdb
          astcanary
          CORE-SOUNDS-EN-WAV
          CORE-SOUNDS-EN-GSM
          CORE-SOUNDS-EN-G722
          MOH-OPSOUND-WAV
          MOH-OPSOUND-GSM
          MOH-OPSOUND-G722
          EXTRA-SOUNDS-EN-WAV
          EXTRA-SOUNDS-EN-GSM
          EXTRA-SOUNDS-EN-G722

  asterisk-configure-18:
    desc: Prepare Asterisk 18 sources
    dir: '{{.BUILD_DIR}}/asterisk-18'
    cmds:
    - task: asterisk-configure
      vars:
        ASTDIR: '{{.BUILD_DIR}}/asterisk-18'
        DISABLED_CONFS: >-
          oss
          portaudio
          jack
          x11
          vpb
          gtk2
          gmime
          sdl
          avcodec
          bluetooth
          iodbc
          imap
          inotify
          sqlite
          sndfile
          mysqlclient
          postgres
          iksemel
          openr2
          radius
          resample
          spandsp
          tds
          neon29
          neon
          pri
          ss7
          dahdi
          misdn
          suppserv
          tonezone
          fftw3
          unbound
          vorbis
          speex
          speexdsp
          ogg
          ilbc
          opus
          opusfile
          vpb
        MENU_ENABLE: >-
          LOW_MEMORY
          func_speex
          res_snmp
          app_url
          app_flash
        MENU_DISABLE: >-
          BUILD_NATIVE
          codec_speex
          codec_ilbc
          codec_lpc10
          codec_g726
          codec_adpcm
          cdr_syslog
          cdr_sqlite3_custom
          cel_sqlite3_custom
          format_gsm
          format_wav_gsm
          format_siren7
          format_siren14
          format_ilbc
          format_g719
          format_g723
          format_g726
          format_h263
          format_h264
          format_vox
          res_fax
          res_fax_spandsp
          res_format_attr_h263
          res_format_attr_h264
          res_config_pgsql
          res_format_attr_siren14
          res_format_attr_siren7
          res_format_attr_vp8
          res_format_attr_ilbc
          res_speech
          res_config_ldap
          res_format_attr_silk
          res_adsi
          res_monitor
          app_festival
          app_mp3
          app_ices
          app_image
          app_sms
          app_nbscat
          app_test
          chan_sip
          chan_skinny
          chan_unistim
          chan_iax2
          chan_mgcp
          chan_motif
          astdb2sqlite3
          astdb2bdb
          astcanary
          CORE-SOUNDS-EN-WAV
          CORE-SOUNDS-EN-GSM
          CORE-SOUNDS-EN-G722
          MOH-OPSOUND-WAV
          MOH-OPSOUND-GSM
          MOH-OPSOUND-G722
          EXTRA-SOUNDS-EN-WAV
          EXTRA-SOUNDS-EN-GSM
          EXTRA-SOUNDS-EN-G722

  asterisk-configure-20:
    desc: Prepare Asterisk 20 sources
    dir: '{{.BUILD_DIR}}/asterisk-20'
    cmds:
    - task: asterisk-configure
      vars:
        ASTDIR: '{{.BUILD_DIR}}/asterisk-20'
        DISABLED_CONFS: >-
          portaudio
          jack
          x11
          gtk2
          gmime
          sdl
          avcodec
          bluetooth
          iodbc
          imap
          inotify
          sndfile
          mysqlclient
          postgres
          iksemel
          openr2
          radius
          resample
          spandsp
          tds
          neon29
          neon
          pri
          ss7
          dahdi
          tonezone
          fftw3
          unbound
          vorbis
          speex
          speexdsp
          ogg
          ilbc
          opus
          opusfile
        MENU_ENABLE: >-
          LOW_MEMORY
          func_speex
          res_snmp
          app_flash
        MENU_DISABLE: >-
          BUILD_NATIVE
          codec_speex
          codec_ilbc
          codec_lpc10
          codec_g726
          codec_adpcm
          cdr_sqlite3_custom
          cel_sqlite3_custom
          format_gsm
          format_wav_gsm
          format_siren7
          format_siren14
          format_ilbc
          format_g719
          format_g723
          format_g726
          format_h263
          format_h264
          format_vox
          res_fax
          res_fax_spandsp
          res_format_attr_h263
          res_format_attr_h264
          res_config_pgsql
          res_format_attr_siren14
          res_format_attr_siren7
          res_format_attr_vp8
          res_format_attr_ilbc
          res_speech
          res_config_ldap
          res_format_attr_silk
          res_adsi
          res_monitor
          app_festival
          app_mp3
          app_sms
          app_test
          chan_sip
          chan_skinny
          chan_unistim
          chan_iax2
          chan_mgcp
          chan_motif
          astdb2sqlite3
          astdb2bdb
          astcanary
          CORE-SOUNDS-EN-WAV
          CORE-SOUNDS-EN-GSM
          CORE-SOUNDS-EN-G722
          MOH-OPSOUND-WAV
          MOH-OPSOUND-GSM
          MOH-OPSOUND-G722
          EXTRA-SOUNDS-EN-WAV
          EXTRA-SOUNDS-EN-GSM
          EXTRA-SOUNDS-EN-G722

  asterisk-mk-ln:
    internal: true
    vars:
      ASTDIR:
        sh: find -maxdepth 1 -type d -name 'asterisk-{{.ASTVER}}.*'
    preconditions:
      - test -n "{{.ASTVER}}"
      - sh: test ! -d asterisk-{{.ASTVER}}
        msg: Directory asterisk-{{.ASTVER}} exists
    dir: '{{.BUILD_DIR}}'
    cmds:
      - ln -sr {{.ASTDIR}} asterisk-{{.ASTVER}}
      
  asterisk-extract-sources:
    desc: Extract Asterisk sources
    preconditions:
      - test -n "{{.ASTVER}}"
      - test -d "{{.BUILD_DIR}}/download"
    dir: '{{.BUILD_DIR}}/download'
    cmds:
      - tar -xf asterisk-{{.ASTVER}}-current.tar.gz -C {{.BUILD_DIR}}
      - task: asterisk-mk-ln

  old-asterisk-extract-sources:
    desc: Extract Asterisk sources (OLD)
    preconditions:
      - test -n "{{.ASTVER}}"
      - test -d "{{.BUILD_DIR}}/download"
    dir: '{{.BUILD_DIR}}/download'
    cmds:
      - tar -xf asterisk-{{.ASTVER}}.tar.gz -C {{.BUILD_DIR}}
   
  asterisk-build:
    desc: Build Asterisk
    preconditions:
      - test -n "{{.ASTVER}}"    
    dir: '{{.BUILD_DIR}}/asterisk-{{.ASTVER}}'
    env:
      OPTIMIZE: '-fmerge-constants'
    cmds:
      - make -j$(nproc)

  asterisk-install-headers:
    desc: Install Asterisk headers
    preconditions:
      - test -n "{{.ASTVER}}"
    dir: '{{.BUILD_DIR}}/asterisk-{{.ASTVER}}'
    env:
      DESTDIR: '{{.BUILD_DIR}}/install'
    cmds:
      - make install-headers

  cmake-extract:
    desc: Extract CMake sources
    preconditions:
      - test -n "{{.CMAKEVER}}"
      - test -d "{{.BUILD_DIR}}/download"
    dir: '{{.BUILD_DIR}}/download'
    cmds:
      - tar -xf cmake-{{.CMAKEVER}}.tar.gz -C {{.BUILD_DIR}}
  
  cmake-bootstrap:
    desc: Bootstrap CMake
    preconditions:
      - test -n "{{.CMAKEVER}}"
    dir: '{{.BUILD_DIR}}/cmake-{{.CMAKEVER}}'
    cmds:
      - ./bootstrap --prefix=/usr --parallel=$(nproc) --no-debugger

  cmake-make:
    desc: Compile CMake
    preconditions:
      - test -n "{{.CMAKEVER}}"
    cmds:
      - make -j$(nproc) -C {{.BUILD_DIR}}/cmake-{{.CMAKEVER}}

  cmake-install:
    desc: Install CMake
    preconditions:
      - test -n "{{.CMAKEVER}}"
      - test -d {{.BUILD_DIR}}/cmake-{{.CMAKEVER}}
    env:
      DESTDIR: '{{.BUILD_DIR}}/install'
    cmds:
      - make install -C {{.BUILD_DIR}}/cmake-{{.CMAKEVER}}

  chan-quectel-clone:
    desc: Fetch chan-quectel sources
    preconditions:
      - test -n "{{.PRESET}}"
    dir: '{{.BUILD_DIR}}'
    cmds:
      - git clone -q --branch={{.BRANCH}} http://github.com/RoEdAl/asterisk-chan-quectel.git chan-quectel

  chan-quectel-preset:
    desc: Create CMake presets
    dotenv: ['{{.BUILD_DIR}}/buildflags.env']
    preconditions:
      - test -n "{{.PRESET}}"
    dir: '{{.BUILD_DIR}}/chan-quectel'
    cmds:
      - cmd: |
          {
            ./get-source-date-epoch.sh
            {{if .RPI_VERSION}}echo 'TOOLSET_TARGET_RPI={{.RPI_VERSION}}'{{end}}
          } >> {{.BUILD_DIR}}/.env
        silent: true
      - ./get-build-flags.sh {{.PRESET}}-env > CMakeUserPresets.json

  chan-quectel-package:
    desc: Build chan_quectel packages
    preconditions:
      - test -n "{{.PRESET}}"
    dir: '{{.BUILD_DIR}}/chan-quectel'
    cmds:
      - >-
        cmake --preset={{.PRESET}}
        {{if .CC_TOOLCHAIN}}--toolchain=cmake/toolchain/{{.CC_TOOLCHAIN}}.toolchain.cmake{{end}}
        {{if .ASTERISK_VERSION_NUM}}-DASTERISK_VERSION_NUM={{.ASTERISK_VERSION_NUM}}{{end}}
      - cmake --build --preset=package-{{.PRESET}}
