version: '3'

includes:
  20.04:
    taskfile: 20.04
    dir: ../../ubuntu/20.04
    aliases: [focal, focal-fossa]
  22.04:
    taskfile: 22.04
    dir: ../../ubuntu/22.04
    aliasses: [jammy, jammy-jellyfish]
  24.04:
    taskfile: 24.04
    dir: ../../ubuntu/24.04
    aliases: [noble, noble-numbat]

tasks:
  armhf:
    desc: Build chan_quectel for ARM on Ubuntu using GNU Toolchain
    deps:
    - 20.04:armhf
    - 22.04:armhf
    - 24.04:armhf
  
  arm64:
    desc: Build chan_quectel for ARM64 on Ubuntu using GNU Toolchain
    deps:
    - 20.04:arm64
    - 22.04:arm64
    - 24.04:arm64
