version: '3'

includes:
  10:
    taskfile: 10
    dir: 10
    aliases: [buster]
  11:
    taskfile: 11
    dir: 11
    aliases: [bullseye]
  12:
    taskfile: 12
    dir: 12
    aliases: [bookworm]

tasks:
  clean:
    desc: Remove package directories
    deps:
    - 10:clean
    - 11:clean
    - 12:clean

  native:
    aliases: [default]
    desc: Build chan_quectel on Debian
    deps:
    - 10:native
    - 11:native
    - 12:native

  armhf:
    desc: Build chan_quectel for ARM on Debian
    deps:
    - 10:armhf
    - 11:armhf
    - 12:armhf

  rpi*:
    desc: Build chan_quectel for Raspberry Pi on Debian
    deps:
    - 10:rpi{{index .MATCH 0}}
    - 11:rpi{{index .MATCH 0}}
    - 12:rpi{{index .MATCH 0}}

  arm64:
    desc: Build chan_quectel for ARM64 on Debian
    deps:
    - 10:arm64
    - 11:arm64
    - 12:arm64
