version: '3'

output: prefixed

vars:
  BUILD_DIR: /build
  UBU_ROOT: '{{.BUILD_DIR}}/cache'

tasks:
  asterisk-headers:
    desc: Copy Asterisk header files
    preconditions:
      - test -d {{.UBU_ROOT}}
    cmds:
      - mkdir -p {{.BUILD_DIR}}/asterisk-headers
      - cp {{.UBU_ROOT}}/usr/include/asterisk.h {{.BUILD_DIR}}/asterisk-headers
      - cp -r {{.UBU_ROOT}}/usr/include/asterisk {{.BUILD_DIR}}/asterisk-headers
