version: '3'

includes:
  builder:
    taskfile: ../../builder
    internal: true

vars:
  RPI_DEBIAN_10_ASTERISK_VERSION_NUM: 163000

tasks:
  clean:
    desc: Remove package directory
    status:
    - test ! -d package
    cmds:
    - rm -rf package

  native:
    desc: Build chan_quectel on Raspberry Pi OS (Buster)
    aliases: [default]
    prompt: This operation takes a lot of time. Do you want to continue?
    vars:
      IMG_NAME: 'asterisk-dev/chan-quectel:debian-10.rpi'
      TMP_DIR:
        sh: mktemp -d --suffix={{randInt 0 1000}}
      GIT_BRANCH:
        sh: git branch --show-current
    cmds:
    - task: builder:native:build-img
      vars:
        TARGET: chan-quectel
        IMG_NAME: '{{.IMG_NAME}}'
        IID_FILE: '{{.TMP_DIR}}/img-base.id'
        DOCKER_PLATFORM: 'linux/arm/v6'
    - task: builder:native:build
      vars:
        BASEIMG: '{{.IMG_NAME}}'
        PRESET: deb
        BRANCH: '{{.GIT_BRANCH}}'
        IID_FILE: '{{.TMP_DIR}}/img.id'
        ASTERISK_VERSION_NUM: '{{.RPI_DEBIAN_10_ASTERISK_VERSION_NUM}}'
        DOCKER_PLATFORM: 'linux/arm/v6'
    - task: builder:copy-pkgs
      vars:
        DST_DIR: ''
        DOCKER_IMG:
          sh: cat {{.TMP_DIR}}/img.id
        DOCKER_PLATFORM: 'linux/arm/v6'
    - defer: rm -rf {{.TMP_DIR}}
    - defer: docker image rm $(cat {{.TMP_DIR}}/img.id) > /dev/null

