version: '3'

dotenv:
- .env
- docker.env

includes:
  debian:
    taskfile: debian
    dir: debian
  rpi-debian:
    taskfile: rpi-debian
    dir: rpi-debian
  ubuntu:
    taskfile: ubuntu
    dir: ubuntu
  centos:
    taskfile: centos
    dir: centos
  ext:
    taskfile: arm-gnu-toolchain
    aliases: [arm-gnu-toolchain]

tasks:
  clean:
    desc: Delete build directories
    deps:
    - debian:clean
    - rpi-debian:clean
    - centos:clean
  
  native:
    aliases: [default]
    desc: Build chan_quectel
    deps:
    - debian:native
    - centos:native
