version: '3'

includes:
  builder:
    taskfile: ../../builder
    internal: true
    vars:
      OSNAME: 'debian-12.rpi'
      ASTERISK_VERSION_NUM: 200100
      DOCKER_PLATFORM: 'linux/arm/v6'    

tasks:
  clean:
    desc: Remove package directory
    status:
    - test ! -d package
    cmds:
    - rm -rf package

  native:
    desc: Build chan_quectel on Raspberry Pi OS (Bookworm)
    aliases: [default]
    prompt: This operation takes a lot of time. Do you want to continue?
    deps:
      - builder:platform