version: '3'

includes:
  builder:
    taskfile: ../../../builder
    dir: ../../../ubuntu/24.04
    internal: true
    vars:
      OSNAME: 'ubuntu-24.04'
      ASTERISK_VERSION_NUM: 200000

tasks:
  armhf:
    desc: Build chan_quectel for ARM on Ubuntu 24.04 using GNU Toolchain
    deps:
      - builder:armhf-ext

  arm64:
    desc: Build chan_quectel for ARM64 on Ubuntu 24.04 using GNU Toolchain
    deps:
      - builder:arm64-ext
