version: '3'

output: prefixed

vars:
  BUILD_DIR: /build

dotenv:
  - '{{.BUILD_DIR}}/.env'
  - '.env'

tasks:
  install-pkgs:
    desc: Install specified packages (RPM)
    cmds:
    - cmd: yum update -y -q
      silent: true
    - yum install -y -q {{.CLI_ARGS}}    

  create-dotenv:
    desc: Create .env file (RPM)
    status:
      - test -f {{.BUILD_DIR}}/.env
    cmds:
    - cmd: |
        {
          echo "CFLAGS='$(rpm -E '%optflags')'"
          echo "CXXFLAGS='$(rpm -E '%optflags')'"
          echo "LDFLAGS='$(rpm -E '%__global_ldflags')'"
        } > {{.BUILD_DIR}}/.env
      silent: true      
