version: '3'

includes:
  builder:
    taskfile: ../../builder
    internal: true
    vars:
      OSNAME: 'ubuntu-22.04'
      ASTERISK_VERSION_NUM: 181000

tasks:
  clean:
    desc: Remove package directory
    status:
      - test ! -d package
    cmds:
      - rm -rf package

  native:
    desc: Build chan_quectel on Ubuntu 22.04
    aliases: [default]
    deps:
      - builder:native

  armhf:
    desc: Build chan_quectel for ARM on Ubuntu 22.04
    deps:
      - builder:armhf

  arm64:
    desc: Build chan_quectel for ARM64 on Ubuntu 22.04
    deps:
      - builder:arm64
