version: '3'

includes:
  10:
    taskfile: 10
    dir: ../../debian/10
    aliases: [buster]

  11:
    taskfile: 11
    dir: ../../debian/11
    aliases: [bullseye]

  12:
    taskfile: 12
    dir: ../../debian/12
    aliases: [bookworm]

tasks:
  armhf:
    desc: Build chan_quectel for ARM on Debian using GNU Toolchain
    deps:
    - 10:armhf
    - 11:armhf
    - 12:armhf

  rpi*:
    desc: Build chan_quectel for Raspberry Pi on Debian using GNU Toolchain
    deps:
    - 10:rpi{{index .MATCH 0}}
    - 11:rpi{{index .MATCH 0}}
    - 12:rpi{{index .MATCH 0}}

  arm64:
    desc: Build chan_quectel for ARM64 on Debian using GNU Toolchain
    deps:
    - 10:arm64
    - 11:arm64
    - 12:arm64
