version: '3'

includes:
  builder:
    taskfile: ../../../builder
    dir: ../../../debian/11
    internal: true
    vars:
      OSNAME: 'debian-11'
      ASTERISK_VERSION_NUM: 180000    

vars:
  DEBIAN_11_ASTERISK_VERSION_NUM: 180000

tasks:
  armhf:
    desc: Build chan_quectel for ARM on Debian Bullseye using GNU Toolchain
    deps:
      - builder:armhf-ext

  rpi*:
    desc: Build chan_quectel for Raspberry Pi on Debian Bullseye using GNU Toolchain
    vars:
      RPI_VERSION: '{{index .MATCH 0|default 1}}'
    deps:
      - task: builder:rpi-ext
        vars:
          RPI_VERSION: '{{.RPI_VERSION}}'
  
  arm64:
    desc: Build chan_quectel for ARM64 on Debian Bullseye using GNU Toolchain
    deps:
      - builder:arm64-ext
