name: Install required packages
description: Install required packages
runs:
  using: composite
  steps:
    - name: Install packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: |
          git wget
          build-essential
          libasound2-dev libsqlite3-dev asterisk-dev
  
    - name: Git configuration
      shell: bash
      run: git config --global advice.detachedHead false
