version: '3'

includes:
  builder:
    taskfile: ../../builder
    internal: true
    vars:
      OSNAME: 'centos7.8'
      ASTERISK_VERSION_NUM: 180000

tasks:
  clean:
    desc: Remove package directory
    status:
    - test ! -d package
    cmds:
    - rm -rf package

  native:
    desc: Build chan_quectel on CentOS 7.8
    aliases: [default]
    deps:
      - builder:centos