version: '3'

output: prefixed

vars:
  BUILD_DIR: /build

dotenv:
  - '{{.BUILD_DIR}}/.env'
  - '.env'

tasks:
  download-and-extract:
    internal: true
    required:
      vars: [DOWNLOAD_URL]    
    dir: '{{.BUILD_DIR}}/cmake'
    cmds:
      - curl --silent --show-error -L {{.DOWNLOAD_URL}} -o - | tar -zxf - --strip-components=1

  download:
    desc: Download and extract CMake sources
    preconditions:
      - test -s {{.BUILD_DIR}}/cache/cmake-latest.json
      - test -r {{.BUILD_DIR}}/cache/cmake-latest.json
    vars:
      DOWNLOAD_URL:
        sh: cat {{.BUILD_DIR}}/cache/cmake-latest.json | jq --raw-output '.tarball_url'
      SOURCE_DATE_EPOCH:
        sh: cat {{.BUILD_DIR}}/cache/cmake-latest.json | jq --raw-output '.created_at|fromdateiso8601'
      SOURCE_DATE:
        sh: cat {{.BUILD_DIR}}/cache/cmake-latest.json | jq --raw-output '.created_at'
    cmds:
      - task: download-and-extract
        vars:
          DOWNLOAD_URL: '{{.DOWNLOAD_URL}}'
      - cmd: echo 'SOURCE_DATE_EPOCH={{.SOURCE_DATE_EPOCH}}' > {{.BUILD_DIR}}/cmake/.env
        silent: true
      - cmd: echo 'SOURCE_DATE_EPOCH={{.SOURCE_DATE_EPOCH}}' '#' '{{.SOURCE_DATE}}' 1>&2
        silent: true
  
  bootstrap:
    desc: Bootstrap CMake
    dotenv: ['{{.BUILD_DIR}}/cmake/.env']
    dir: '{{.BUILD_DIR}}/cmake'
    cmds:
      - ./bootstrap --prefix=/usr --parallel=$(nproc) --no-debugger

  build:
    desc: Build CMake
    dotenv: ['{{.BUILD_DIR}}/cmake/.env']
    cmds:
      - make -j$(nproc) -C {{.BUILD_DIR}}/cmake

  install:
    desc: Install CMake
    dotenv: ['{{.BUILD_DIR}}/cmake/.env']
    env:
      DESTDIR: '{{.BUILD_DIR}}/install'
    cmds:
      - make install -C {{.BUILD_DIR}}/cmake
      - find {{.BUILD_DIR}}/install -mindepth 1 -type d -exec touch -c -d "@${SOURCE_DATE_EPOCH}" '{}' +
      - find {{.BUILD_DIR}}/install -mindepth 1 -type f -exec touch -c -d "@${SOURCE_DATE_EPOCH}" '{}' +
