version: '3'

includes:
  builder:
    taskfile: ../../../builder
    dir: ../../../debian/12
    internal: true
    vars:
      OSNAME: 'debian-12'
      ASTERISK_VERSION_NUM: 200100    

tasks:
  armhf:
    desc: Build chan_quectel for ARM on Debian Bookworm using GNU Toolchain
    deps:
      - builder:armhf-ext

  rpi*:
    desc: Build chan_quectel for Raspberry Pi on Debian Bookworm using GNU Toolchain
    vars:
      RPI_VERSION: '{{index .MATCH 0|default 1}}'
    deps:
      - task: builder:rpi-ext
        vars:
          RPI_VERSION: '{{.RPI_VERSION}}'

  arm64:
    desc: Build chan_quectel for ARM64 on Debian Bookworm using GNU Toolchain
    deps:
      - builder:arm64-ext
