version: '3'

includes:
  7.8:
    taskfile: 7.8
    dir: 7.8
    aliases: [freepbx]

tasks:
  clean:
    desc: Remove package directories
    deps:
    - '7.8:clean'

  native:
    desc: Build chan_quectel on CentOS
    aliases: [default]
    deps:
    - '7.8:native'
