#
# Building chan_quectel
#
name: Build channel

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]
  push:

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: 17
        check-path: src

  build:
    runs-on: ubuntu-latest
    needs: formatting-check
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ./.github/actions/install-required-packages
    - name: Configure project
      run: cmake -P make-build-dir.cmake
    - name: Build
      run: cmake -P build-chan-quectel.cmake
