#
# Building and bublishing packages: Debian and OpenWRT
#
name: Build packages

permissions:
  contents: write

on:
  push:
    tags: v202*.*.*
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  OWRTVER: 22.03.5
  UBUNTU_DISTRO: ubuntu22.04

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout actions
      uses: actions/checkout@v3
      with:
        sparse-checkout: .github/actions
        sparse-checkout-cone-mode: false
    - uses: ./.github/actions/install-required-packages

  build-deb-pkg:
    needs: pre-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ./.github/actions/install-required-packages
    - name: Install lintian
      env:
        DEBIAN_FRONTEND: noninteractive
      run: sudo apt-get install -qq lintian
   
    - name: Configure project
      run: cmake -P make-build-dir.cmake

    - name: Build packages
      run: cmake -P make-package.cmake

    - name: Check package
      run: lintian --verbose --info package/asterisk-chan-quectel_*.deb

    - name: Archive DEB
      uses: actions/upload-artifact@v3
      with:
        name: pkg-deb
        path: |
          package/asterisk-chan-quectel_*.deb
          package/asterisk-chan-quectel_*.deb.sha256
        retention-days: 1
        if-no-files-found: error

    - name: Archive TAR.GZ
      uses: actions/upload-artifact@v3
      with:
        name: pkg-tar-gz
        path: |
          package/asterisk-chan-quectel_*.tar.gz
          package/asterisk-chan-quectel_*.tar.gz.sha256
        retention-days: 1
        if-no-files-found: error

  deb-pkg-try-install:
    needs: build-deb-pkg
    env:
      DEBIAN_FRONTEND: noninteractive
    runs-on: ubuntu-latest
    steps: 
    - name: Install gdebi package
      run: sudo apt-get install -qq gdebi-core
    - uses: actions/download-artifact@v3
      with:
        name: pkg-deb
        path: deb
    - name: Install package
      working-directory: deb
      run: |
        for p in $(ls *.deb); do
          echo "::notice::Installing package $p"
          sudo gdebi --non-interactive $p
        done

  build-deb-pkg-arch:
    needs: pre-build
    strategy:
      matrix:
        arch: [armv7, aarch64]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ./.github/actions/install-required-packages
    - uses: uraimo/run-on-arch-action@v2
      name: Build package (${{ matrix.arch }})
      with:
        arch: ${{ matrix.arch }}
        distro: ${{ env.UBUNTU_DISTRO }}
        githubToken: ${{ github.token }}
        install: |
          apt-get update -qq -y
          apt-get install -qq -y git cmake \
            build-essential \
            libsqlite3-dev libasound2-dev asterisk-dev
          git config --global --add safe.directory /home/runner/work/asterisk-chan-quectel/asterisk-chan-quectel
        env: |
          DEBIAN_FRONTEND: noninteractive
        run: |
          cmake -P make-build-dir.cmake
          cmake -P make-package.cmake
    - name: Install lintian
      env:
        DEBIAN_FRONTEND: noninteractive
      run: sudo apt-get install -qq -y lintian
    - name: Check package
      run: lintian --verbose --info package/asterisk-chan-quectel_*.deb
    - name: Archive DEB
      uses: actions/upload-artifact@v3
      with:
        name: pkg-deb-${{ matrix.arch }}
        path: |
          package/asterisk-chan-quectel_*.deb
          package/asterisk-chan-quectel_*.deb.sha256
        retention-days: 1
        if-no-files-found: error
    - name: Archive TAR.GZ
      uses: actions/upload-artifact@v3
      with:
        name: pkg-tar-gz-${{ matrix.arch }}
        path: |
          package/asterisk-chan-quectel_*.tar.gz
          package/asterisk-chan-quectel_*.tar.gz.sha256
        retention-days: 1
        if-no-files-found: error
    - uses: uraimo/run-on-arch-action@v2
      name: Try to instal package (${{ matrix.arch }})
      with:
        arch: ${{ matrix.arch }}
        distro: ${{ env.UBUNTU_DISTRO }}
        setup: |
          mkdir -p "${PWD}/package"
        dockerRunArgs: |
          --volume "${PWD}/package:/package"
        install: |
          apt-get update -qq -y
          apt-get install -qq -y gdebi-core
        env: |
          DEBIAN_FRONTEND: noninteractive
        run: |
          gdebi --non-interactive package/asterisk-chan-quectel_*.deb || echo "::error::Could not install package ${{ matrix.arch }}"
  
  build-openwrt-pkg:
    runs-on: ubuntu-latest
    needs: pre-build
    strategy:
      matrix:
        arch: [x86-64, x86-generic, ramips-mt7620, bcm47xx-generic, bcm63xx-generic, sunxi-cortexa7, sunxi-cortexa8, sunxi-cortexa53, armvirt-32, rockchip-armv8, bcm27xx-bcm2708]
        include:
          - arch: sunxi-cortexa7
            eabi: true
          - arch: sunxi-cortexa8
            eabi: true
          - arch: bcm27xx-bcm2708
            eabi: true
          - arch: armvirt-32
            eabi: true
    steps:
    - name: Checkout actions
      uses: actions/checkout@v3
      with:
        sparse-checkout: |
          .github/actions
        sparse-checkout-cone-mode: false
    - uses: ./.github/actions/install-required-packages
    - uses: ./.github/actions/install-openwrt-sdk
      with:
        openwrt-version: ${{ env.OWRTVER }}
        arch: ${{ matrix.arch }}
        eabi: ${{ matrix.eabi }}
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: asterisk-modules/asterisk-chan-quectel

    - name: Configure project
      run: cmake -P asterisk-modules/asterisk-chan-quectel/make-build-dir.cmake

    - name: Generate OpenWRT Makefile
      run: cmake -P asterisk-modules/asterisk-chan-quectel/install-openwrt-makefile.cmake

    - name: Check OpenWRT SDK config file
      id: check-owrt-cfg
      uses: andstor/file-existence-action@v2
      with:
        files: "owrtsdk/${{ matrix.arch }}/.config"

    - name: Prepare OpenWRT SDK (symlink)
      run: |
        owrtsdk=$(cd owrtsdk; pwd)
        cd asterisk-modules/asterisk-chan-quectel/install/openwrt
        ln -sf ${owrtsdk}/${{ matrix.arch }} ${{ matrix.arch }}

    - name: Prepare OpenWRT SDK (files)
      if: steps.check-owrt-cfg.outputs.files_exists != 'true'
      working-directory: asterisk-modules/asterisk-chan-quectel/install/openwrt
      run: cp feeds-strskx.conf diffconfig build-opk.sh ${{ matrix.arch }}

    - name: Prepare OpenWRT SDK (feeds)
      if: steps.check-owrt-cfg.outputs.files_exists == 'true'
      working-directory: asterisk-modules/asterisk-chan-quectel/install/openwrt/${{ matrix.arch }}
      run: ./scripts/feeds install asterisk-chan-quectel

    - name: Build OpenWRT packages
      working-directory: asterisk-modules/asterisk-chan-quectel/install/openwrt/${{ matrix.arch }}
      run: ./build-opk.sh
    - name: Archive IPK
      uses: actions/upload-artifact@v3
      with:
        name: ipk-${{ matrix.arch }}
        path: asterisk-modules/asterisk-chan-quectel/install/openwrt/${{ matrix.arch }}/bin/packages/*/strskx/*.ipk
        retention-days: 1
        if-no-files-found: error

  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: [build-openwrt-pkg, deb-pkg-try-install, build-deb-pkg-arch]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
  
    - name: Publish packages
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          **/asterisk-chan-quectel*.tar.gz
          **/asterisk-chan-quectel*.tar.gz.sha256
          **/asterisk-chan-quectel*.deb
          **/asterisk-chan-quectel*.deb.sha256
          **/asterisk-chan-quectel*.ipk
